theme: jekyll-theme-cayman
title: Properties of communities in news outlets in Quotebank
description: The goal of the project is to highlight relationships between newspapers, journalists and interviewees. More precisely, we want to cluster media outlets based on who they cite. We will then analyze the attributes of the resulting communities using external datasets. Some of the factor we want to examine are geolocation, interviewees, owner, size, focus, etc.
